### PR TITLE
Feat/vendor card

### PR DESCRIPTION
**Pull request by ccmelas**
Adds the vendor card feature.
Issue #7

### CODE REVIEW

**Comment by owonwo** [comment]
@ccmelas Did you know the issue you resolve was for #2  not #7 ?

**Comment by NotJohs** [comment]
@owonwo so that's taken care of.

**Comment by owonwo** [comment]
@NotJohs are you done ?

**Comment by owonwo** [comment]
@ccmelas this is the link for the vendor list component [Designs Spec](https://xd.adobe.com/spec/aa269db1-f4a5-41e5-4872-a1d41ea658ce-dc17/screen/7e403c6a-82fd-431b-821c-f40727a5e6e7/Design-System/)

**Pull request merged**
